// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkonbphrqcalcjlymsss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrb25icGhycWNhbGNqbHltc3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzk3MTksImV4cCI6MjA3MDY1NTcxOX0.eeJnW4I9TT36LingdHmAbfxnTLrOWe1XmHi38LtOuHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});